# .streamlit/secrets.toml
SUPABASE_URL = "https://oeuhdztwdrrsbutfebtx.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...."
GRAPHHOPPER_API_KEY = "e56cd8b8-d293-4338-bc7b-b8fb40a787e9"
SUPABASE_PASS = "0mKDi4Ko3KFX3EKO"
OCR_SPACE = "K89531747788957"
ORS_API_KEY = "5b3ce3597851110001cf624826a7314029a546c9a60d65b222e9255a"
GOOGLE_MAPS_API_KEY = "AIzaSyCjuvDt8vX1BiAMtLmpvWcUzKFwRSzreJ8"
[gcp_credentials]
type = "service_account"
project_id = "routemind-vision"
private_key_id = "38f9e086351de889b088d12ca47adf045e6dfa43"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDE1haHqRHpGHpz
6B9u1gK9uLmY+tSbTOfFchAJMEo0uclUTXXJBk+CDVjaF0IHXQSpLbzpO79QOJqK
4a8+hvEVRMgxf+Y0kpgFtx0Mad/XFSS29a9DxpvT/rAhm72TAKT1O51lFZvyezQ3
ZyhRSxCzlq0jQ7jGCHZNx0VnodRX9LfJnFPuahvLyU/X19H98a7wBU6X3FFkApNu
ZYji65TCVJz5MWFVa+VZtUPJoZke6QIUkAnRV30o6Wo0mTQzM6EVxE+gm+dN7t9z
13tp5VSTjvpQDbPUb/WurOcAbPfSb++Rge/RtvBZmov+GtzoBNYY/SdlOe7SWMgV
UVdPQZUhAgMBAAECggEAJE1Cnvbuu3FdBhrhjzCvlTtoGV9rThAHL8o7TGKIUQSR
rbdSeYZtK/RXtnMzJYYBec0aad5vyHUEBYidaBf9hvlmPYDT3U7K9ETi+drd4j4/
RPH3RrXun9C5PZ2KPz4Pbj32J4IufnA7/1rKXAHO3Pw1Rsty3K0LWoldksENF0JT
Fx8WodkWGdUZWVFBLZ0A2PdkTIQuQtL8t0/J07UwS/31V0w04LmLrIqX2gRH8OQK
DMmR0NvvDsV3eTRsa4MowFMJLDBBMnGJ/CjJ63vt3Ao0RtVdlpjcVUEkgZ5MLUTF
JfURU63pTlM4ZwAiU+eK+c4phIOvuv11P0wXg78rBQKBgQDvwj1e9ORtGsETPazl
J3meFZLv0ilc5NxSaTnnd8sVW828w9yrV30xLgcTR9PUo4z+mCqm4FNNgNRAT0Sj
zCp8k1ekNmix7FQvtSHWMi+jx3LcgCzFjIxRD/G340R0t/ocs1f8gMqpJet/1Tj/
+8a6XdEqhyuNbye7r0kMqiOWXQKBgQDSK4Lc1KHZDb6NXTmGEaB2byyqcMcDHGWO
NeEpyuy7rPIX9xIVtkq+nFJexd0U6lgcx12+WKFGu74hAyuOeJ0WDefxngIln9Du
OO9OjY/IBaZbu0nX5j/fsHGTxyejMf4ashq8roouqNuEDmVI2eHRbG5zIk4bRED/
VebaHNRFlQKBgQC7TwSjKq9KjZxJa+WnIS/iUPh6Y7Xs3N9DgvG549zE0vPohRvg
wHkN8ueUKIlVlnCQdlDcDmUGJ5+qnkMBtH9805+kqt0gI4Ghw+CrdonBahBSM9DG
hQcaTVqKTwMsLI853OLgYb3yZ62UMQBW/FxFPQYsM23TEQP5nPd07XbgAQKBgEJt
cj0uD8G08Gdp8caIR7lnRizQ3HYFQawDJ5m4A78F2LbuZo7qQRGiAv7ldw0nTJY8
BUsmZEMhD+ULRXcQdEYGOytJD9CohLbm0+x2Hd3Qu1X/CkXtBn9DG4LjzYltQa1a
Yc0FNbOtt0Qz8JtoElHI/dfyHdHMbubFVePWfNlJAoGAeBqgeDWgVoaeQUS6UoEL
90p3CfbaLHd4vzfr0bawWO0By5A9cx60vFRK9lZ3lxSlvIe2kigbatSCgfPn1lGD
uNPho1uBIVWRmSxfTY8M1k1cdFf+LMmRiFXZ+vTWPQqvOtwgzKH90kB7ZpfoJ9To
ldxyLFloY092zYcvUXmsTxc=
-----END PRIVATE KEY-----"""
client_email = "vision@routemind-vision.iam.gserviceaccount.com"
client_id = "104031111663644781256"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/vision%40routemind-vision.iam.gserviceaccount.com"
universe_domain = "googleapis.com"